ROOT := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

CC 			= cc
AR 			= ar -rcs
RM 			= rm -f
MKDIR 		= mkdir -p
CFLAGS 		= -Wall -Werror -Wextra -fPIC
INCLUDES	= -I$(ROOT)/headers

# ──────────────────────── #
#        ANSI COLORS       #
# ──────────────────────── #
RED        := \033[0;31m
GREEN      := \033[0;32m
BLUE       := \033[0;34m
RESET      := \033[0m
